#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker build -t cornellappdev/transit-python:"$TRAVIS_COMMIT" --no-cache .
docker push cornellappdev/transit-python:"$TRAVIS_COMMIT"
